parallelize: True
stages:
# pretraining
 - name: atmosurface+sst-sst
   stage: train
   chain_jobs: 3
   base_config: config/master_ocean.yml
   config_files:
    - config/ocean_overwrite.yml
   options:
    - streams_directory=./config/streams/ocean_master/
    - wgtags.grid=master-coupling-ocean-01
    - wgtags.exp=atmosurface+sst-sst

 - name: rad+atmosurface+sst-sst
   stage: train
   chain_jobs: 3
   base_config: config/master_ocean_overwrite.yml
   config_files:
    - config/ocean_overwrite.yml
   options:
    - streams_directory=./config/streams/ocean_master_rad/
    - wgtags.grid=master-coupling-ocean-01
    - wgtags.exp=rad+atmosurface+sst-sst