parallelize: True
stages:
# pretraining
 - name: sst-sst
   stage: train
   chain_jobs: 3
   base_config: config/master_ocean.yml
   config_files:
    - config/ocean_overwrite.yml
   options:
    - streams_directory=./config/streams/ocean_master_only_sst/
    - ae_local_num_blocks=0 # disable local assimilation for just sst
    - streams.ERA5-Ocean.source=["sst"]
    - wgtags.grid=master-coupling-ocean-01
    - wgtags.exp=sst-sst

 - name: atmosurface-sst
   stage: train
   chain_jobs: 3
   base_config: config/master_ocean.yml
   config_files:
    - config/ocean_overwrite.yml
   options:
    - streams_directory=./config/streams/ocean_master/
    - wgtags.grid=master-coupling-ocean-01
    - wgtags.exp=atmosurface-sst

 - name: rad+atmosurface-sst
   stage: train
   chain_jobs: 3
   base_config: config/master_ocean.yml
   config_files:
    - config/ocean_overwrite.yml
   options:
    - streams_directory=./config/streams/ocean_master_rad/
    - wgtags.grid=master-coupling-ocean-01
    - wgtags.exp=rad+atmosurface-sst