parallelize: True
stages:
# no radiation
 - name: tiny-24hx1
   stage: train
   base_config: config/master_ocean.yml
   chain_jobs: 2
   config_files:
    - config/tiny_overwrite.yml
    - config/large_dt_overwrite.yml
   options:
    - "wgtags.exp='tiny-24hx1-freq'"
 - name: ft-tiny-24hx1
   stage: train
   from_run_id: STAGE.tiny-24hx1
   config_files:
    - config/config_forecasting_finetuning.yml
   options:
    - "wgtags.exp='ft-tiny-24hx1-freq'"
# radiation
 - name: tiny-24hx1-rad
   stage: train
   base_config: config/master_ocean.yml
   chain_jobs: 2
   config_files:
    - config/tiny_overwrite.yml
    - config/radiation_stream_overwrite.yml
    - config/large_dt_overwrite.yml
   options:
    - "wgtags.exp='tiny-24hx1-rad-freq'"
 - name: ft-tiny-24hx1-rad
   stage: train
   from_run_id: STAGE.tiny-24hx1-rad
   config_files:
    - config/config_forecasting_finetuning.yml
   options:
    - "wgtags.exp='ft-tiny-24hx1-rad-freq'"