parallelize: True 
stages:
 - name: atmo-atmo_ft
   stage: train
   chain_jobs: 3
   from_run_id: m91ehu6z
   config_files:
    - config/master_ocean_finetuning.yml
   options:
    - wgtags.exp=atmo-atmo_ft

 - name: sst+atmo-atmo_ft
   stage: train
   chain_jobs: 3
   from_run_id: g2xxepr3
   config_files:
    - config/master_ocean_finetuning.yml
   options:
    - wgtags.exp=sst+atmo-atmo_ft

 - name: sst+atmo-atmo+rad_ft
   stage: train
   chain_jobs: 3
   from_run_id: qws8i6pi
   config_files:
    - config/master_ocean_finetuning.yml
   options:
    - wgtags.exp=sst+atmo-atmo+rad_ft