# (C) Copyright 2025 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

freeze_modules: ".*global.*|.*local.*|.*adapter.*|.*q_cells.*|.*latent.*|.*ERA5.*|.*ERA5-Ocean.*|.*ERA5-radiation.*"

general:
  # mutable parameters
  istep: 0  

# config for training
training_config:
  num_mini_epochs: 16
  start_date: 2014-01-01T00:00
  
  learning_rate_scheduling :
    lr_start: 1e-6
    lr_max: 1e-4
    lr_final_decay: 2e-6
    lr_final: 0.0
    num_steps_warmup: 256
    num_steps_cooldown: 512
    policy_warmup: "cosine"
    policy_decay: "cosine"
    policy_cooldown: "linear"
    parallel_scaling_policy: "sqrt"

  forecast :
      offset: 1
      num_steps: 10 # originally 16 TODO: check for OOM reduce to 12, target 4 days => adjust for longer steps 8 ~0.095 s/sec 12 OOM 10 ~ 0.076
      policy: "fixed"

