parallelize: True
stages:
# Ocean =======================
  - name: infer_sst-sst_ft
    stage: inference
    from_run_id: qc40r555
    slurm_args:
     - '--time=06:00:00'
# -----------------------------
  - name: infer_atmosurface-sst_ft
    stage: inference
    from_run_id: gw5v14ad
    slurm_args:
     - '--time=06:00:00'
  - name: infer_atmosurface-sst_ft-forcing
    stage: inference
    from_run_id: fjw7q6c7
    slurm_args:
     - '--time=06:00:00'
# -----------------------------
  - name: infer_rad+atmosurface-sst_ft
    stage: inference
    from_run_id: uee15i99
    slurm_args:
     - '--time=06:00:00'
  - name: infer_rad+atmosurface-sst_ft-forcing
    stage: inference
    from_run_id: y31vb6kj
    slurm_args:
     - '--time=06:00:00'
# export Ocean =================
  - name: export_sst-sst_ft
    stage: export
    format: "netcdf"
    outpu-dir: "/capstor/scratch/cscs/sgrasse/export_data"
    from_run_id: STAGE.infer_sst-sst_ft
  - name: export_atmosurface-sst_ft
    stage: export
    format: "netcdf"
    outpu-dir: "/capstor/scratch/cscs/sgrasse/export_data"
    from_run_id: STAGE.infer_atmosurface-sst_ft
  - name: export_atmosurface-sst_ft-forcing
    stage: export
    format: "netcdf"
    outpu-dir: "/capstor/scratch/cscs/sgrasse/export_data"
    from_run_id: STAGE.infer_atmosurface-sst_ft-forcing
  - name: export_rad+atmosurface-sst_ft
    stage: export
    format: "netcdf"
    outpu-dir: "/capstor/scratch/cscs/sgrasse/export_data"
    from_run_id: STAGE.infer_rad+atmosurface-sst_ft
  - name: export_rad+atmosurface-sst_ft-forcing
    stage: export
    format: "netcdf"
    outpu-dir: "/capstor/scratch/cscs/sgrasse/export_data"
    from_run_id: STAGE.infer_rad+atmosurface-sst_ft-forcing