parallelize: True
stages:
  - name: infer_atmo-atmo_pt
    stage: inference
    from_run_id: js6ffvw0
    config_files:
     - config/config_short_forecast.yml
    slurm_args:
     - '--time=00:30:00'
  - name: infer_atmo-atom_ft
    stage: inference
    from_run_id: gw9ubto2
    config_files:
     - config/config_short_forecast.yml
    slurm_args:
     - '--time=00:30:00'
# -----------------------------
  - name: infer_sst+atmo-atmo_pt
    stage: inference
    from_run_id: sso03cvj
    config_files:
     - config/config_short_forecast.yml
    slurm_args:
     - '--time=00:30:00'
  - name: infer_sst+atmo-atom_ft
    stage: inference
    from_run_id: gw9ubto2
    config_files:
     - config/config_short_forecast.yml
    slurm_args:
     - '--time=00:30:00'
# -----------------------------
  - name: infer_sst+atmo-atmo+rad_pt
    stage: inference
    from_run_id: aejy29gs
    config_files:
     - config/config_short_forecast.yml
    slurm_args:
     - '--time=00:30:00'
  - name: infer_sst+atmo-atom+rad_ft
    stage: inference
    from_run_id: w31y9ktt
    config_files:
     - config/config_short_forecast.yml
    slurm_args:
     - '--time=00:30:00'
# --------------------------------
  - name: eval_short_forecast
    stage: evaluation
    run_ids:
     - STAGE.infer_atmo-atmo_pt
     - STAGE.infer_atmo-atom_ft
     - STAGE.infer_sst+atmo-atmo_pt
     - STAGE.infer_sst+atmo-atom_ft
     - STAGE.infer_sst+atmo-atmo+rad_pt
     - STAGE.infer_sst+atmo-atom+rad_ft
    eval_config: config/short_forecast_eval.yml