ae_local_dim_embed: 256 # reduced from 2048 => keep compression factor ~2
ae_local_num_blocks: 0
ae_local_num_heads: 16

ae_adapter_embed: 128
ae_adapter_num_heads: 16

ae_global_num_blocks: 4
ae_global_dim_embed: 1024 # reduced from 2048

fe_num_blocks: 10 # reduce to 10, 12? original: 16
fe_layer_norm_after_blocks: [4] # reduce to ~fe_num_blocks // 2 original 7
